//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MEDDBContainer : DbContext
    {
        public MEDDBContainer()
            : base("name=MEDDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Illness> IllnessSet { get; set; }
        public virtual DbSet<MedCard> MedCardSet { get; set; }
        public virtual DbSet<Documents> DocumentsSet { get; set; }
        public virtual DbSet<Person> PersonSet { get; set; }
        public virtual DbSet<DoctorRecord> DoctorRecordSet { get; set; }
        public virtual DbSet<VisitInfo> VisitInfoSet { get; set; }
        public virtual DbSet<FreeTime> FreeTimeSet { get; set; }
        public virtual DbSet<WorkTime> WorkTimeSet { get; set; }
    }
}
