//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitInfo
    {
        public int Doctor { get; set; }
        public string OperatorFullName { get; set; }
        public System.DateTime OperatorBirthDate { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateFinish { get; set; }
    
        public virtual Operator Operator { get; set; }
        public virtual WorkTime WorkTime { get; set; }
    }
}
